name = "discord-thread-tracker"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# Configure the schedule for the worker (runs every hour)
[triggers]
crons = ["*/5 * * * *"] # Run once every 5 minutes

# Configure environment variables
[vars]
# Do not put actual secrets here - they will be defined using wrangler secret commands

# Configure D1 database bindings
[[d1_databases]]
binding = "DB"
database_name = "discord_threads_db"
database_id = "b2154043-8311-44e6-923a-20a7e610a76b"

[observability]
enabled = true
head_sampling_rate = 0.1 # 10% of requests are logged