name = "discord-thread-tracker"
main = "src/index.js"
compatibility_date = "2023-05-18"

# Configure the schedule for the worker (runs every hour)
[triggers]
crons = ["0 * * * *"] # Run once every hour

# Configure environment variables
[vars]
# Do not put actual secrets here - they will be defined using wrangler secret commands

# Configure D1 database bindings
[[d1_databases]]
binding = "DB"
database_name = "discord_threads_db"
database_id = "b2154043-8311-44e6-923a-20a7e610a76b"
